"""add_property_management_fields

Revision ID: 1578db3df019
Revises: e5f6a7b8c9d0
Create Date: 2026-02-19 01:53:58.480509
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1578db3df019'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leases_unit_id_fkey', 'leases', type_='foreignkey')
    op.create_foreign_key(None, 'leases', 'units', ['unit_id'], ['id'])
    op.drop_constraint('payments_lease_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_applied_to_charge_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'rent_charges', ['applied_to_charge_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'leases', ['lease_id'], ['id'])
    op.add_column('properties', sa.Column('is_property_managed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('properties', sa.Column('management_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('properties', sa.Column('leasing_fee_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.drop_constraint('rent_charges_lease_id_fkey', 'rent_charges', type_='foreignkey')
    op.create_foreign_key(None, 'rent_charges', 'leases', ['lease_id'], ['id'])
    op.drop_constraint('units_property_id_fkey', 'units', type_='foreignkey')
    op.create_foreign_key(None, 'units', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.create_foreign_key('units_property_id_fkey', 'units', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rent_charges', type_='foreignkey')
    op.create_foreign_key('rent_charges_lease_id_fkey', 'rent_charges', 'leases', ['lease_id'], ['id'], ondelete='CASCADE')
    op.drop_column('properties', 'leasing_fee_amount')
    op.drop_column('properties', 'management_fee_pct')
    op.drop_column('properties', 'is_property_managed')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_applied_to_charge_id_fkey', 'payments', 'rent_charges', ['applied_to_charge_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_lease_id_fkey', 'payments', 'leases', ['lease_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.create_foreign_key('leases_unit_id_fkey', 'leases', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
