"""add_rule_engine

Revision ID: 2cfba3d4848b
Revises: 8b6e58c318b3
Create Date: 2026-02-17 21:13:59.344763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfba3d4848b'
down_revision: Union[str, None] = '8b6e58c318b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorization_rules', sa.Column('category_string', sa.String(length=255), nullable=True))
    op.add_column('categorization_rules', sa.Column('negate_amount', sa.Boolean(), nullable=False))
    op.alter_column('categorization_rules', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorization_rules', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('categorization_rules', 'negate_amount')
    op.drop_column('categorization_rules', 'category_string')
    # ### end Alembic commands ###
