"""manual_accounts

Revision ID: 8b6e58c318b3
Revises: ab8a42ef4c86
Create Date: 2026-02-17 20:06:46.250693
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6e58c318b3'
down_revision: Union[str, None] = 'ab8a42ef4c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('institution_name', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('is_manual', sa.Boolean(), nullable=False))
    op.alter_column('accounts', 'plaid_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('accounts', 'plaid_account_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'plaid_account_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('accounts', 'plaid_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('accounts', 'is_manual')
    op.drop_column('accounts', 'institution_name')
    # ### end Alembic commands ###
