"""make_transaction_account_id_nullable

Revision ID: ac1826cd7110
Revises: d8118e15a88f
Create Date: 2026-02-18 03:03:52.196134
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1826cd7110'
down_revision: Union[str, None] = 'd8118e15a88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
