"""add_property_financials

Revision ID: b46fc3ad161e
Revises: f3063b2d4857
Create Date: 2026-02-17 16:33:25.126699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46fc3ad161e'
down_revision: Union[str, None] = 'f3063b2d4857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('monthly_rent', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('properties', sa.Column('mortgage_monthly', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('properties', sa.Column('property_tax_annual', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('properties', sa.Column('insurance_annual', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('properties', sa.Column('hoa_monthly', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('properties', sa.Column('maintenance_monthly', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'maintenance_monthly')
    op.drop_column('properties', 'hoa_monthly')
    op.drop_column('properties', 'insurance_annual')
    op.drop_column('properties', 'property_tax_annual')
    op.drop_column('properties', 'mortgage_monthly')
    op.drop_column('properties', 'monthly_rent')
    # ### end Alembic commands ###
