"""add_mortgage_balance

Revision ID: d4abaa3592ed
Revises: b46fc3ad161e
Create Date: 2026-02-17 18:13:54.926923
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4abaa3592ed'
down_revision: Union[str, None] = 'b46fc3ad161e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('mortgage_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'mortgage_balance')
    # ### end Alembic commands ###
