"""add_is_ignored_and_rule_action

Revision ID: d8118e15a88f
Revises: 3dce31e6c0fd
Create Date: 2026-02-18 02:11:10.183947
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8118e15a88f'
down_revision: Union[str, None] = '3dce31e6c0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('categorization_rules', sa.Column(
        'action', sa.String(length=20), nullable=False, server_default='categorize'))
    op.add_column('transactions', sa.Column(
        'is_ignored', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_ignored')
    op.drop_column('categorization_rules', 'action')
    # ### end Alembic commands ###
