"""initial_tables

Revision ID: f3063b2d4857
Revises: 
Create Date: 2026-02-17 15:46:15.478272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3063b2d4857'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_household_id'), 'categories', ['household_id'], unique=False)
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_investments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_real_estate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_debts', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_snapshots_household_id'), 'net_worth_snapshots', ['household_id'], unique=False)
    op.create_index(op.f('ix_net_worth_snapshots_snapshot_date'), 'net_worth_snapshots', ['snapshot_date'], unique=False)
    op.create_table('plaid_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_plaid_items_household_id'), 'plaid_items', ['household_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_valuation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_household_id'), 'properties', ['household_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_index(op.f('ix_accounts_household_id'), 'accounts', ['household_id'], unique=False)
    op.create_index(op.f('ix_accounts_plaid_item_id'), 'accounts', ['plaid_item_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_household_id'), 'budgets', ['household_id'], unique=False)
    op.create_table('categorization_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('match_field', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_value', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_rules_household_id'), 'categorization_rules', ['household_id'], unique=False)
    op.create_table('property_valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_valuations_property_id'), 'property_valuations', ['property_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.String(length=255), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_holdings_household_id'), 'holdings', ['household_id'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('plaid_investment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('security_id', sa.String(length=255), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_investment_transaction_id')
    )
    op.create_index(op.f('ix_investment_transactions_account_id'), 'investment_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_date'), 'investment_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_investment_transactions_household_id'), 'investment_transactions', ['household_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('plaid_category', sa.String(length=255), nullable=True),
    sa.Column('plaid_category_id', sa.String(length=50), nullable=True),
    sa.Column('custom_category_id', sa.UUID(), nullable=True),
    sa.Column('is_manual_category', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['custom_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_household_id'), 'transactions', ['household_id'], unique=False)
    op.create_index(op.f('ix_transactions_plaid_transaction_id'), 'transactions', ['plaid_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_plaid_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_household_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_investment_transactions_household_id'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_date'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_account_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_holdings_household_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_property_valuations_property_id'), table_name='property_valuations')
    op.drop_table('property_valuations')
    op.drop_index(op.f('ix_categorization_rules_household_id'), table_name='categorization_rules')
    op.drop_table('categorization_rules')
    op.drop_index(op.f('ix_budgets_household_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_accounts_plaid_item_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_household_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_household_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_plaid_items_household_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    op.drop_index(op.f('ix_net_worth_snapshots_snapshot_date'), table_name='net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_snapshots_household_id'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_index(op.f('ix_categories_household_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('households')
    # ### end Alembic commands ###
